name: Bug Report
description: Report a bug in LEANN
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      placeholder: |
        1. Install with...
        2. Run command...
        3. See error
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error message
      description: Paste any error messages
      render: shell

  - type: input
    id: version
    attributes:
      label: LEANN Version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Docker
    validations:
      required: true
