name: Feature Request
description: Suggest a new feature for LEANN
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or need
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example usage
      description: Show how the API might look
      render: python
